# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('photo_filename', models.CharField(blank=True, default='', max_length=250)),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('short_description', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gallery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_gallery',
            },
        ),
    ]
